# Generated by Django 5.0.4 on 2024-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0003_application_resume_customuser_resume_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
