# Generated by Django 5.0.4 on 2024-06-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0004_customuser_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(max_length=20),
        ),
    ]
