# Generated by Django 5.0.4 on 2024-06-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening_app', '0005_alter_customuser_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
    ]
